//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBillDetail
    {
        public int ID { get; set; }
        public Nullable<int> BookBillID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public Nullable<bool> Returned { get; set; }
        public Nullable<int> BookBillReturnID { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    }
}
