//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Icon { get; set; }
        public string Path { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<bool> Visible { get; set; }
    }
}
